/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_net168_audiorecord_opensles_OpenSLESRecord */

#ifndef _Included_com_net168_audiorecord_opensles_OpenSLESRecord
#define _Included_com_net168_audiorecord_opensles_OpenSLESRecord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_net168_audiorecord_opensles_OpenSLESRecord
 * Method:    _initRecord
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_net168_audiorecord_opensles_OpenSLESRecord__1initRecord
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_net168_audiorecord_opensles_OpenSLESRecord
 * Method:    _stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_net168_audiorecord_opensles_OpenSLESRecord__1stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_net168_audiorecord_opensles_OpenSLESRecord
 * Method:    _start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_net168_audiorecord_opensles_OpenSLESRecord__1start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_net168_audiorecord_opensles_OpenSLESRecord
 * Method:    _release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_net168_audiorecord_opensles_OpenSLESRecord__1release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_net168_audiorecord_opensles_OpenSLESRecord
 * Method:    _getState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_net168_audiorecord_opensles_OpenSLESRecord__1getState
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_net168_audiorecord_opensles_OpenSLESRecord
 * Method:    _setNativeCallback
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_net168_audiorecord_opensles_OpenSLESRecord__1setNativeCallback
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
