/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tiffany_audiorecord_tester_NativeAudioTester */

#ifndef _Included_com_tiffany_audiorecord_tester_NativeAudioTester
#define _Included_com_tiffany_audiorecord_tester_NativeAudioTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tiffany_audiorecord_tester_NativeAudioTester
 * Method:    nativeStartCapture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_tiffany_audiorecord_tester_NativeAudioTester_nativeStartCapture
  (JNIEnv *, jobject);

/*
 * Class:     com_tiffany_audiorecord_tester_NativeAudioTester
 * Method:    nativeStopCapture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_tiffany_audiorecord_tester_NativeAudioTester_nativeStopCapture
  (JNIEnv *, jobject);

/*
 * Class:     com_tiffany_audiorecord_tester_NativeAudioTester
 * Method:    nativeStartPlayback
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_tiffany_audiorecord_tester_NativeAudioTester_nativeStartPlayback
  (JNIEnv *, jobject);

/*
 * Class:     com_tiffany_audiorecord_tester_NativeAudioTester
 * Method:    nativeStopPlayback
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_tiffany_audiorecord_tester_NativeAudioTester_nativeStopPlayback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
